services:
  frontend:
    image: ihuska2004/quirknotes_frontend
    ports:
    - "3000:80"

  backend:
    image: ihuska2004/quirknotes_backend
    ports:
    - "4000:4000"
    environment:
    - ENV=Docker
    depends_on:
    - mongodb

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"